### ISSUE TITLE
Correzioni

### ISSUE THREAD

**Issue by Alby7503** [Exyss/university-notes#31]
Slide 60
- Il 2o caso non è completo
- La formula di ricorrenza dovrebbe essere T(n) = α * T(n / β) + f(n)

Slide 61
- Nell'esempio dove α=9 e β=2, nella formula subito sotto la base del logaritmo (β) diventa 3

Slide 62
- il +0.1 dovrebbe essere all'esponente (al 2o esempio)

7.4
- C'è un 7 di troppo ad inizio paragrafo

Come richiesta generale potresti includere i file .tex? Sia per rimanere open-source e per risparmiarti un po' di tempo

**Comment by Alby7503** [comment]
@Exyss 
![image](https://github.com/Exyss/university-notes/assets/44052142/bbf2dd8e-cfcb-4798-841a-35a654280b3d)

**Comment by Exyss** [comment]
Fixati i typo, thanks

Quanto alla richiesta, per quanto mi dispiacce, per questioni pratiche non posso
