### ISSUE TITLE
Typo Automi

### ISSUE THREAD

**Issue by i0nut02** [Exyss/university-notes#39]
### Nome del file da correggere

Automi, Calcolabilità e Complessità

### Numero della pagina da correggere

10

### Descrizione dell'errore ed eventuale correzione proposta

L'automa non può andate da q1 in q3 con 0 come input, e da q2 a q1

### Screenshot dell'errore

<img width="488" alt="Schermata 2023-10-19 alle 09 17 02" src="https://github.com/Exyss/university-notes/assets/99051485/6c70d5c4-3105-4581-a49c-fe913c1807de">

**Comment by Exyss** [comment]
Si, ho invertito gli ultimi due passi computazionali degli ultimi due rami
