### ISSUE TITLE
[Error] Variabile sbagliata 

### ISSUE THREAD

**Issue by Alby7503** [Exyss/university-notes#47]
### Nome del file da correggere

Basi di Dati 1

### Numero della pagina da correggere

85

### Descrizione dell'errore ed eventuale correzione proposta

Sostituire 1857000 con 6190

### Screenshot dell'errore

![IMG_0556](https://github.com/Exyss/university-notes/assets/44052142/c9edb81c-20e6-443f-b03d-fb020e9e6c0e)

**Comment by Exyss** [comment]
Grazie mille!
