### ISSUE TITLE
[Errors] Errori vari

### ISSUE THREAD

**Issue by Alby7503** [Exyss/university-notes#49]
### Nome del file da correggere

Sistemi Operativi 1

### Numero della pagina da correggere

40, 53, 54, 67, 69, 70

### Descrizione dell'errore ed eventuale correzione proposta

Vedi screenshots

### Screenshot dell'errore

40: mismatch tra singolare e plurale 
![IMG_0561](https://github.com/Exyss/university-notes/assets/44052142/cec5cab3-f420-4466-b119-cb40549c75ca)

53: typo
![IMG_0562](https://github.com/Exyss/university-notes/assets/44052142/c2022d0e-6891-485f-a8e1-e69396caeeb9)

54: ‘a’ suonerebbe meglio 
![IMG_0563](https://github.com/Exyss/university-notes/assets/44052142/46c15e91-7212-4d9e-aa33-6b9383ade531)

67: il RAG proposto come soluzione presenta ancora un deadlock
![IMG_0564](https://github.com/Exyss/university-notes/assets/44052142/ab41f64c-7176-4d9d-ba20-f2c4a7cdc872)

69: t2 non ha pretese (è un thread semplice e di poche parole)
![IMG_0565](https://github.com/Exyss/university-notes/assets/44052142/f67ae887-3537-41a5-9191-047c17974e72)

70: typo
![IMG_0566](https://github.com/Exyss/university-notes/assets/44052142/fc038f0c-d713-41d9-b100-b7683d52da0b)

**Comment by Exyss** [comment]
Come sempre, grazie per le correzioni.

Per quanto riguarda l'errore segnalato a pagina 67, non vi è un deadlock nell'immagine mostrata poiché l'aggiunta della terza risorsa $r_3$ risolve l'attesa circolare. Ho modificato parte della spiegazione sugli appunti per rendere più chiaro il motivo.

Se non ti tornasse ancora fammi sapere, lascerò la issue aperta ancora per qualche giorno

**Comment by Alby7503** [comment]
> Come sempre, grazie per le correzioni.
> 
> Per quanto riguarda l'errore segnalato a pagina 67, non vi è un deadlock nell'immagine mostrata poiché l'aggiunta della terza risorsa r3 risolve l'attesa circolare. Ho modificato parte della spiegazione sugli appunti per rendere più chiaro il motivo.
> 
> Se non ti tornasse ancora fammi sapere, lascerò la issue aperta ancora per qualche giorno

Non avevo considerato che essendo la stessa risorsa non deve necessariamente usare quella “tutta a destra”, grazie del chiarimento 😅
