### ISSUE TITLE
[Error] Typo nella definizione dell'insieme degli stati accettanti del DFA

### ISSUE THREAD

**Issue by Jude-Kal** [Exyss/university-notes#50]
### Nome del file da correggere

Automi Calcolabilità e Complessità

### Numero della pagina da correggere

34

### Descrizione dell'errore ed eventuale correzione proposta

Versione attuale:

F <sub>D</sub> = {R ∈ Q <sub>D</sub>  | R ∩ F  != ∅ }

Versione proposta:

F <sub>D</sub> = {R ∈ Q <sub>D</sub>  | R ∩ F<sub>N</sub>  != ∅ }

**Comment by Exyss** [comment]
Grazie mille
