### ISSUE TITLE
[Typo] Algebra

### ISSUE THREAD

**Issue by Frisbon** [Exyss/university-notes#51]
### Nome del file da correggere

Algebra.pdf

### Numero della pagina da correggere

174

### Descrizione dell'errore ed eventuale correzione proposta

Non é $dfi$ ma $bdi$

### Screenshot dell'errore

![image](https://github.com/Exyss/university-notes/assets/84731341/31c299f9-a4a5-47bd-9fc1-043c5ca8e6d0)

**Comment by Exyss** [comment]
Grazie mille
