### ISSUE TITLE
[Error] Typo's Sistemi Operativi I

### ISSUE THREAD

**Issue by FeddyLix17** [Exyss/university-notes#52]
### Nome del file da correggere

Sistemi Operativi I

### Numero della pagina da correggere

5, 20, 29, 89, 97

### Descrizione dell'errore ed eventuale correzione proposta

pagina 5 indirica invece di indica
![image](https://github.com/Exyss/university-notes/assets/66442720/8f87842b-d5d0-49f6-b057-66b62a838388)

pagina 20 manca il ; alla chiamata di funzione wait(NULL)
![image](https://github.com/Exyss/university-notes/assets/66442720/fa103ca9-ea27-4ef2-9f4f-81633e075e98)

pagina 29 quueue invece di queue
![image](https://github.com/Exyss/university-notes/assets/66442720/b4dff94e-c821-4dc7-8cf3-bf63acbdfe83)

pagina 89 teoreticamente invece di teoricamente
![image](https://github.com/Exyss/university-notes/assets/66442720/f34f5ebc-ada1-4e33-8b1b-af41c073cf01)

pagina 97 inc cui invece di in cui
![image](https://github.com/Exyss/university-notes/assets/66442720/47bd07ea-eb17-4293-a350-c706d8bd81b3)

**Comment by Exyss** [comment]
Grazie mille
