### ISSUE TITLE
[Error] Imprecisione nella riduzione di SAT a 3SAT

### ISSUE THREAD

**Issue by lord-marcel** [Exyss/university-notes#54]
### Nome del file da correggere

Automi, Calcolabilità e Complessità

### Numero della pagina da correggere

140

### Descrizione dell'errore ed eventuale correzione proposta

Nella parte in cui si suppone l'insoddisfacibilità di $\phi$ e si vuole concludere con l'insoddisfacibilità di $\phi'$, dice _"Supponiamo invece che_ $\phi$ _non sia soddisfacibile. In tal caso, anche_ $C_i$ _deve esserlo, implicando che nessun letterale tra_ $l_1, . . . , l_k$  _sia vero"_, evidentemente generato dal copy-paste del passaggio precedente.

Correzione proposta:
In verità, per ogni possibile assegnamento _almeno_ uno fra i $C_i$ risulta essere falso in ogni suo letterale. A questo punto, supponendo essere $C_j$ la clausola inquisita, si continua come fatto.

### Screenshot dell'errore

![immagine](https://github.com/Exyss/university-notes/assets/36630876/e4b97a8f-fc64-45b5-bb71-f7838a08e4b4)

**Comment by Exyss** [comment]
Grazie mille
