### ISSUE TITLE
[Error] Typo's Basi di Dati I

### ISSUE THREAD

**Issue by FeddyLix17** [Exyss/university-notes#55]
### Nome del file da correggere

Basi di Dati I

### Numero della pagina da correggere

2, 16, 25, 26, 34

### Descrizione dell'errore ed eventuale correzione proposta

alcuni typo di battitura e altri sull'ordine dei termini (invertiti) per la rinomina di un attributo

### Screenshot dell'errore

![image](https://github.com/Exyss/university-notes/assets/66442720/cf6e6142-eb2f-4e4a-887f-4d272d088339)

![image](https://github.com/Exyss/university-notes/assets/66442720/b72dba29-b89e-493a-a5bc-3abf193557c1)

![image](https://github.com/Exyss/university-notes/assets/66442720/2a4a33db-9e0b-4a08-abc7-232e16781c9b)

![image](https://github.com/Exyss/university-notes/assets/66442720/c9ae8433-a097-4426-8fd0-b5e393ab3cec)

![image](https://github.com/Exyss/university-notes/assets/66442720/c156b1d7-4ac6-4846-9e67-8089366d7121)

**Comment by Exyss** [comment]
Grazie mille
