### ISSUE TITLE
[Typo] ALGO2

### ISSUE THREAD

**Issue by Frisbon** [Exyss/university-notes#57]
### Nome del file da correggere

Progettazione di Algoritmi

### Numero della pagina da correggere

25

### Descrizione dell'errore ed eventuale correzione proposta

> Spero di non aver frainteso, altrimenti scusa il disturbo.

Teorema 5 afferma che in un grafo diretto ciclico esiste un DFS (tale che) "trova" un arco all'indietro.
Nei due esempi sono archi in avanti, non all'indietro
![WhatsApp Image 2024-03-14 at 13 38 28_9bbfb5cb](https://github.com/Exyss/university-notes/assets/84731341/73358d51-a032-4810-b5be-deec852e3a24)

### Screenshot dell'errore

![image](https://github.com/Exyss/university-notes/assets/84731341/32f0033d-1ea7-4da1-9162-f59aadf506bf)

**Comment by Exyss** [comment]
Entrambi gli esempi che hai descritto sono due archi all'indietro

**Comment by Frisbon** [comment]
Stupida confusione con i versi del $⊆ $
Sorry
