### ISSUE TITLE
[Error] errore commento codice assembly

### ISSUE THREAD

**Issue by rimaout** [Exyss/university-notes#58]
### Nome del file da correggere

Architettura degli Elaboratori.pdf

### Numero della pagina da correggere

pag 17

### Descrizione dell'errore ed eventuale correzione proposta

Errore:
sub $t0, $t0, $s3 // $t0 = $t0 + $s3 ossia $t0 = 12 - 18

Correzione:
sub $t0, $t0, $s3 // $t0 = $t0 - $s3 ossia $t0 = 12 - 18

### Screenshot dell'errore

<img width="469" alt="image" src="https://github.com/Exyss/university-notes/assets/116072651/297ef62f-f61b-4133-97c6-c8de1e9908e0">

**Comment by Exyss** [comment]
Grazie mille :)
