### ISSUE TITLE
[Error] Typo's Reti di Elaboratori

### ISSUE THREAD

**Issue by FeddyLix17** [Exyss/university-notes#60]
### Nome del file da correggere

Reti di Elaboratori

### Numero della pagina da correggere

20, 33, 41

### Descrizione dell'errore ed eventuale correzione proposta

- pagina 20 alla definizione 15, ***attente*** invece di ***attende***
- pagina 33
    - nell'esempio di richieste usando il protocollo POP3, dopo il comando *retr 2*, ***<message 1 contents>*** invece di ***<message 2 contents>***
    - ***a attivata*** invece di ***attivata***
 - pagina 41, nella lista di comandi FTP, ***MDK*** invece di ***MKD*** 

### Screenshot dell'errore

![image](https://github.com/Exyss/university-notes/assets/66442720/1deae3a3-8333-4bab-8e70-711bd42f4c13)
![image](https://github.com/Exyss/university-notes/assets/66442720/484bf7b8-f2b4-4c96-b3b3-952b9bed5633)
![image](https://github.com/Exyss/university-notes/assets/66442720/1aacffdd-efe8-4d22-9ef5-8aa2c5e87eba)

**Comment by Exyss** [comment]
Grazie mille 🏂🏼
