### ISSUE TITLE
[Error] Typo's Reti di Elaboratori

### ISSUE THREAD

**Issue by FeddyLix17** [Exyss/university-notes#62]
### Nome del file da correggere

Reti di Elaboratori

### Numero della pagina da correggere

11, 12

### Descrizione dell'errore ed eventuale correzione proposta

- pagina 11 $\Large 10^3$ invece di $\Large 10^4$

- pagina 12 $\Large L_2$ invece di $\Large L_3$

### Screenshot dell'errore

![image](https://github.com/Exyss/university-notes/assets/66442720/311ba80f-2758-4419-b921-ba2fd0f92430)

<div align="center">

![image](https://github.com/Exyss/university-notes/assets/66442720/1afcc73a-7460-46b9-889b-6f90430a9410)

</div>

**Comment by Exyss** [comment]
Grazie mille!
