### ISSUE TITLE
[Error] Typo's Sistemi Operativi II

### ISSUE THREAD

**Issue by FeddyLix17** [Exyss/university-notes#63]
### Nome del file da correggere

Sistemi Operativi II

### Numero della pagina da correggere

2, 3, 9, 10, 14. 26, 29, 42, 46, 48, 66, 70, 74, 75, 99, 100, 101, 106, 137, 138, 139, 140

### Descrizione dell'errore ed eventuale correzione proposta

- pagina 2: tali invece di tale

- pagina 3: grafo invece di grado

- pagina 9: -r invece di -R

- pagina 10: uguale a pagina 9

- pagina 14: contenete invece di contenere (2 volte)

- pagina 26: >> invece di >

- pagina 29: processo invece di process

- pagina 42: operazione invece di operazioni

- pagina 46: precedente invece di successiva (\n)

- pagina 48: 00111 invece di 00101 (per >>)

- pagina 66: %d invece di %p (primo printf)

- pagina 70: stdio invece di stdin

- pagina 74: assegnare una stringa come str=“ciao” (invece che ad esempio con strcpy) porta a un [Undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior) a meno che non si insericsca manualmente il carattere \0

- pagina 75: come pag 74 e l'ultima malloc presenta un ulteriore parametro

- pagina 99: intero invece di interno

- pagina 100: <sys/mann,h> invece di <sys/mann.h>

- pagina 101: c’è un aperto di troppo

- pagina 106: legge invece di scrive

- pagina 112: clock invece di lock

- pagina 137: omunicazione invece di comunicazione

- pagina 138: implicido invece di implicito

- pagina 139: direettamente invece di direttamente

- pagina 140: attender invece di attendere

### Screenshot dell'errore

- pagina 2
![image](https://github.com/user-attachments/assets/5f223c6b-86ae-4361-9b44-980473ad3b9c)

- pagina 3
![image](https://github.com/user-attachments/assets/85753936-259f-4b5f-bffe-52ebed5403aa)

- pagina 9
![image](https://github.com/user-attachments/assets/fc5b29c8-8689-46a5-8ed3-3c25071eb418)

- pagina 10
![image](https://github.com/user-attachments/assets/3828af73-a900-486c-8a33-6885ddb52fa9)

- pagina 14
![image](https://github.com/user-attachments/assets/0afbfeba-6341-4767-beb6-c7a05b3629ca)

- pagina 26
![image](https://github.com/user-attachments/assets/5ce25650-37f5-4e5e-98e3-efe81264c456)

- pagina 29
![image](https://github.com/user-attachments/assets/7c381d2c-363a-49ea-b8ec-ac0f48318278)

- pagina 42
![image](https://github.com/user-attachments/assets/b98301e2-d02a-4384-91bc-5c84449293b6)

- pagina 46
![image](https://github.com/user-attachments/assets/523ffeeb-5ec1-4a14-b715-5cb904aa5f01)

- pagina 48
![image](https://github.com/user-attachments/assets/81a24439-5232-415f-9aa7-71772c3338e8)

- pagina 66
![image](https://github.com/user-attachments/assets/b5bf0fa9-08ef-4c70-81f0-19b4865f761d)

- pagina 70
![image](https://github.com/user-attachments/assets/ddc549eb-0416-4bfe-9ddd-d654c5dc5f28)

- pagina 74
![image](https://github.com/user-attachments/assets/30acd0d0-6c43-46a6-bf36-c148f6ee94a7)

- pagina 75
![image](https://github.com/user-attachments/assets/611d88d8-2c9f-413d-b912-39847d24c985)

- pagina 99
![image](https://github.com/user-attachments/assets/9e04e1eb-65f7-40bf-9ff7-e552a327b68b)

- pagina 100
![image](https://github.com/user-attachments/assets/5bc3ea0b-f3ab-445f-9e3a-3dffd75df202)

- pagina 101
![image](https://github.com/user-attachments/assets/e32cc737-6b82-4562-8951-c51a1d68b6bd)

- pagina 106
![image](https://github.com/user-attachments/assets/9a712bbc-79d6-4ff7-b43e-e9d323e0e688)

- pagina 112
![image](https://github.com/user-attachments/assets/2ce2a4d4-1041-4ad3-93f4-617599f335d8)

- pagina 137
![image](https://github.com/user-attachments/assets/e542dacf-0c03-4ce1-b530-8858dc4d244a)

- pagina 138
![image](https://github.com/user-attachments/assets/ce373ff1-c141-4e13-8499-5913472f679b)

- pagina 139
![image](https://github.com/user-attachments/assets/6f36f7f9-c9e0-4e2d-a1fc-88f20c9b2ce0)

- pagina 140
![image](https://github.com/user-attachments/assets/9be69ce9-b306-4959-a606-0dca3f761689)

**Comment by Exyss** [comment]
Grazie mille come sempre
