### ISSUE TITLE
[Enhancement] Automi chiusura dell'unione in REG

### ISSUE THREAD

**Issue by gpelisset** [Exyss/university-notes#64]
### Nome del file da migliorare

Automi

### Numero della pagina da migliorare

15

### Descrizione dell'eventuale miglioria proposta

La funzione $\delta$ a fine pagina e' mal posta se $Q_1 \cap Q_2 \ne \emptyset$. Si dovrebbe assumere $Q_1 \cap Q_2 \ne \emptyset$ oppure ridefinire gli stati in $Q_1$ e $Q_2$ mediante funzioni $f_1 \colon Q_1 \hookrightarrow \mathbb{N}$ e $f_2 \colon Q_2 \hookrightarrow \mathbb{N}$ tali che $f_1(Q_1) \cap f_2(Q_2) = \emptyset$ e porre $Q := f_1(Q_1) \sqcup f_2(Q_2) \sqcup \\{ q_0 \\}$ dove $q_0 \notin f_1(Q_1) \cup f_2(Q_2)$. Alternativamente, uno potrebbe mantenere la stessa definizione di $Q$, ma, nei sostituire i primi due casi della definizione di $\delta$ con $\chi_{Q_1}(q) \delta_1(q, a) \cup \chi_{Q_2}(q) \delta_2(q, a)$ dove $\chi_A(b)C = C$ se $b \in A$ altrimenti $\emptyset$.

### Screenshot

![Screenshot from 2024-07-29 12-58-28](https://github.com/user-attachments/assets/dc235e7b-99f3-4503-9cd7-d710ea77172f)

**Comment by Exyss** [comment]
Dimentichi che nel caso degli NFA la funzione $\delta$ non sia una normale funzione ma sia una funzione pariziale e polidroma, dunque può sia ammettere che un input non abbia un output sia che ammettere che un input abbia più output. Difatti, tale caratteristica è proprio ciò che permette agli NFA di essere non deterministici: la funzione $\delta$ può dare output multipli.

**Comment by gpelisset** [comment]
Ho detto che non e' ben posta, non che non sia una funzione parziale o altro. La mia domanda e': dato $q \in Q_1 \cap Q_2$, quale e' il valore di $\delta(q, a)$?

**Comment by Exyss** [comment]
Ripeto, essendo una funzione polidroma, la risposta alla tua domanda è entrambi gli output scritti. Non viene specificato nella definizione in quanto il concetto di non-determinismo degli NFA implica già che $\delta$ sia polidroma.

**Comment by gpelisset** [comment]
OK. Certo la sintassi e' poco comune.
