### ISSUE TITLE
[Error] Non e' noto se k-PATH e' in NL.

### ISSUE THREAD

**Issue by gpelisset** [Exyss/university-notes#66]
### Nome del file da correggere

Automi

### Numero della pagina da correggere

175,157,158

### Descrizione dell'errore ed eventuale correzione proposta

Premetto che non ho seguito il corso e non so chi ha proposto questo problema.

Non e' noto se k-path e' in NL.
Si nota facilmente che k-PATH e' NP-completo visto che HAMPATH si riduce in tempo polinomiale a k-PATH (si itera sulle coppie di nodi del grafo in inpput e si esegue k-PATH con k = |V| - 1 per vedere se c'e' un cammino hamiltoniano). Avessi mostrato che k-PATH fosse in NL, allora k-PATH sarebbe in P, ma allora avrei un problema NP-completo in P. Ecco che P = NP.

L'errore discende direttamente dal teorema 74 in cui si caratterizza NL come l'insieme dei linguaggi verificabili in tempo logaritmico. Nota infatti, che nella dimostrazione della seconda implicazione, le scelte non deterministiche non posso essere fatte in parallelo con l'esecuzione di $V$ a meno che $V$ non legga una sola volta il certificato. Tale assunzione su $V$ non e' stata fatta e quindi la prova non funziona e quindi non e' vero che NL e' equivalente ai linguaggi che possono essere verificati in spazio logaritmico come da definizione di verificatore nelle note.

Testi come il Sanjeev Arora and Boaz Barak definiscono in modo diverso i verificatori per NL dicendo esplicitamente che non devono leggere due volte il certificato. Con tale definizione, la caratterizzazione di NL sussiste e la dimostrazione nel file e' corretta. Purtroppo pero' il verificatore dato per la dimostrazione del problema "k-PATH e' in NL" legge piu' volte il certificato per verificare che i vertici in esso siano diversi e quindi non e' un verificatore valido.

Quindi P = NP rimane aperta.

**Comment by Exyss** [comment]
TL; DR: per favore qualcuno cambi il professore che svolge il corso.

Hai ragione, non ci ho mai pensato minimamente in quanto _erroneamente_ mi sono fidato in modo cieco del professore stesso che insegna il corso (corso di cui lui sa abbastanza poco, è stato messo lì più a riempire un buco che altro ed ha dimostrato più e più volte che le sue conoscenze siano parziali e ogni tanto errate). Ad eempio ricordo eclatante che fece un po' scalpore a lezione fu il suo affermare che UNSAT sia uguale al complemento di SAT, cosa che è ovviamente falsa visto che il complemento di SAT contiene anche formule insensate e non solo formule insoddisfacibili. Quando gli venne fatto notare lui rimase più confuso di noi visto che era profondamente convinto del fatto che fosse vero (disse anche che UNSAT sia coNP-Completo perché è il complemento di SAT, quando invece è puramente un caso fortuito che sia UNSAT che il complemento di SAT siano coNP-Completi).

È vero, la definizione di verificatore in log-space dovrebbe assumere che ogni cella del certificato sia read-once (anche perchè senza tale imposizione potremmo anche dimostrare cose assurde, tipo direttamente che HAMPATH è in NL, è una dimostrazione quasi immediata procedendo per brute-force). Cambierò la definizione basandomi su quella del libro di Arora/Barak, che personalmente preferisco di gran lunga rispetto a quello di Sipser.

Una volta identificato il problema, nascono altre problematiche che scaturiscono da questo, ma facilmente risolvibili:
- Nella dimostrazione del teorema di Immerman-Szelepcsényi il professore svolge dei passaggi in cui il verificatore controlla che il certificato abbia un formato corretto. Ovviamente questo richiede che il cerficato venga letto due volte, una per il suo controllo ed una per il suo utilizzo. Il problema è facilmente risolvibile considerando tali controlli come un'assunzione a priori sul formato del certificato (poiché tanto la condizione di esistenza richiede che ci sia un qualche certificato possibile)
- L'esercizio inerente a "k-PATH in NL" deriva (purtroppo) da una domanda d'esame (a cui ti rimando anche https://github.com/sapienzastudentsnetwork/acc2324/discussions/6) in cui il professore chiedeva ciò: "Determinare se il seguente problema è in NL: Dato un grafo non orientato G = (V,E), due vertici s,t $\in$ V, ed un intero k $\in$ N, stabilire se esiste un cammino da s a t di lunghezza esattamente k". A posteriori ovviamente tale richiesta è assurda in quanto il professore abbia praticamente richiesto di stabilire se P = NP. Per Rasoio di Occam direi che, per l'ennesima volta, sia solo dovuto alla sua conoscenza parziale: visto che PATH è in NL avrà assunto che k-PATH sia anch'esso in NL utilizzando una dimostrazione simile.

Puntualizzo inoltre un'altra cosa: il problema della dimostrazione "k-PATH in NL" non è tanto il fatto che alcune celle del certificato vengano lette più volte, visto che potremmo svolgere quelle operazioni di controllo in "contempoarea" all'esecuzione del programma, bensì il vero problema risulta essere proprio la procedura di controllo dei nodi distinti nel cammino: dovremmo mettere a disposizione delle celle $x_1, \ldots, x_n$, una per nodo di $G$, in modo da marcare la cella $x_i$ quando viene visto il nodo $v_i$ e nel caso in cui una cella sia già marcata poter rifiutare il certificato. Ovviamente però questo richiede spazio polinomiale, quindi non va bene.

Lascio l'issue aperta per un po' casomai volessi discutere di altre problematiche derivanti da questo errore

**Comment by gpelisset** [comment]
Ok. Per quanto riguarda Immerman-Szelepcsényi, ho visto che Sipser lo approccia dando direttamente una macchina di Turing che riconosce ${PATH}^c$.

Al contrario, nelle note ci si riconduce alla ricerca di un verificatore per ${PATH}^c$.
Premetto che il seguente non e' un ragionamento formale.
Pero', nella ricerca di un verificatore logaritmico, anche ammesso che la codifica del certificato sia corretta (step da 1 a 8 della dimostrazione), come si puo', dati $a, b$ tali che $(a, b) \in E_G$ e $\langle s \to a \rangle \in c_i$, verificare che $\langle s \to b \rangle$ sia in $c_{i+1}$ leggendo una sola volta il nastro? Per fare tale verifica devo leggere prima $c_i$ e poi $c_{i+1}$. Quindi devo "salvare" $a$ (oppure equivalentemente $b$) da qualche parte per poter fare il paragone una volta che comincio a leggere $c_{i+1}$. E devo aver salvato, assieme ad $a$ anche tutti i nodi $x$ tale che $\langle s \to x \rangle$ e' in $c_i$ (potenzialmente posso dover salvare anche $m$ nodi e m puo' essere anche essere theta(n) dove n e' la dimensione dell'input). Questo non mi sembra possa essere effettuato in spazio logaritmico senza leggere due volte il nastro su cui si trova il certificato.

![Screenshot from 2024-08-21 15-22-17](https://github.com/user-attachments/assets/2a7f831a-69cb-4df1-b4a3-2870a589e39e)

Di contro, la dimostrazione di Sipser e' piu' simile concettualmente anche se un po' piu' complessa.

**Comment by Exyss** [comment]
Ti aggiorno: ho modificato la dimostrazione e alla fine ho optato per sostituirla quasi interamente con quella presente sul libro di Arora/Barak

**Comment by gpelisset** [comment]
Ok! Ho visto solo ora quella sull'Arora/Barak. Adesso direi che funziona.
