### ISSUE TITLE
[Error] Esercizio DECIDABLE_{TM} e' indecidibile

### ISSUE THREAD

**Issue by gpelisset** [Exyss/university-notes#67]
### Nome del file da correggere

Automi

### Numero della pagina da correggere

118

### Descrizione dell'errore ed eventuale correzione proposta

C'e' qualcosa che non mi torna nella dimostrazione.

$DECIDABLE_{TM}$ viene definito come l'insieme delle macchine di turing il cui linguaggio e' decidibile. Quindi se $\langle M \rangle \in DECIDABLE_{TM}$ non necessariamente $M$ e' un decisore. Potrebbe essere un riconoscitore di $L(M)$, linguaggio per cui pero' esiste un decisore (in tal caso diverso da $M$).

La funzione di riduzione costruisce la macchina $M'$. Tale macchina e' un decisore di $\Sigma^{*}$ se $M$ accetta $w$, ed e' un riconoscitore di $\emptyset$ se $M$ non accetta $w$. In ambo i casi il linguaggio della macchina di Turing prodotta e' decidibile e quindi $f(\langle M, w\rangle) \in DECIDABLE_{TM}$ per cui non e' una riduzione valida.
La natura dell'errore sta nel dire: $M'$ va sempre in loop $\implies f(\langle M, w \rangle) = \langle M' \rangle \not\in DECIDABLE_{TM}$.

Ho pensato una dimostrazione, che pero' non mi sembra molto agevole.
Supponiamo che $DECIDABLE_{TM}$ sia decidibile e deciso da $M'$. Sia allora $M$ come segue

$M$ = "
- Su input $w$
- Chiama $M'(\langle M \rangle)$
- Se $M'$ rifiuta, accetta
- Se $M'$ accetta,
- - interpreta $w = \langle M'', w'\rangle$. Se tale interpretazione fallisce, rifiuta
- - esegui $M''(w)$ e se $M''$ accetta, accetta, altrimenti rifiuta
".

$M$ sembrerebbe mal posta visto che nella seconda riga $M$ ottiene una rappresentazione di se stesso. Questo dovrebbe pero' essere possibile come spiegato da Sipser nel capitolo 6.

Quindi, assumendo che esista $M'$, $M$ e' ben posta.
Pero', se $M'$ rifiuta $(\langle M \rangle)$, vuol dire che il linguaggio di $M$ non e' decidibile. Ma se cio' avviene, $M$ accetta qualunque input, per cui il linguaggio di $M$, risulta decidibile. Quindi e' assurdo che $M'$ rifiuti.

Viceversa, se $M'$ accetta vuol dire che $L(M)$ e' decidibile. Allora $M$, come da costruzione, riconosce $A_{TM}$ che e' indecidibile. Questo e' assurdo poiche' $M'$ ha detto che il linguaggio di $M$ e' decidibile (ossia $M'$ ha detto che $L(M) = A_{TM}$ e' decidibile).
Non mi sono venute in mente dimostrazioni piu' facili...

**Comment by Exyss** [comment]
Hai ragione, far andare $M'$ in loop non è sufficiente. La tua nuova dimostrazione è anche corretta. La riduzione è facilmente risolvibile costruendo $M'$ in modo analogo al tuo, in modo che quando $M$ rifiuta $w$ si abbia che $L(M') = A_{TM}$.

**Comment by gpelisset** [comment]
Ho visto il file aggiustato. Ho notato come abbia proposto un'altra dimostrazione che pero' mi sembra avere una falla. Se infatti, nel punti $i$ della macchina $M'$, $M$ va in loop su $w$, il linguaggio di $M'$ diventa $\emptyset$ che e' decidibile. Al contrario, non accettando $M$ $w$, il linguaggio di $f(\langle M, w\rangle)$ dovrebbe essere indecidibile.

**Comment by Exyss** [comment]
Hai ragione di nuovo! Mi sono dimenticato della possibilità del loop (sono fuori allenamento sulle riduzioni). Però ho trovato un fix, questa volta corretto al 100%. Se nella riga 2 dell'algoritmo di M' scriviamo "Se l'esecuzione rifiuta allora M' rifiuta$ e lasciamo il resto del codice identico otteniamo che $\overline{A_{TM}} \leq_m DECIDABLE$ poiché:
- Se $\langle M, w \rangle \notin A_{TM}$ allora l'esecuzione di $M(w)$ andrà o in loop o rifiuterà, ma in entrambi i casi avremo che $M'$ non accetterà alcuna stringa dunque $L(M) = \varnothing$, concludendo che $\langle M' \rangle \in DECIDABLE$
- Se $\langle M, w \rangle \in A_{TM}$ allora l'esecuzione di $M(w)$ accetterà sempre, dunque $M'$ si comporterà come un riconoscitore di $A_{TM}$ concludendo che $L(M) = A_{TM}$ e quindi che $\langle M' \rangle \notin DECIDABLE$

Per tanto abbiamo che $\langle M, w \rangle \in \overline{A_{TM} \iff \langle M, w \rangle \notin A_{TM} \iff f(\langle M, w \rangle) \in DECIDABLE$, quindi in realtà otteniamo che $DECIDABLE$ non è solo indecidibile ma anche irriconoscibile!

Non mi viene in mente nessuna altra riduzione semplice che possa dimostrare solo l'indecidibilità, quindi credo che per il risultato più debole l'opzione migliore sia evitare la riduzione direttamente come nella tua dimostrazione.

Lascio aperto il commento per un po' questa volta, casomai abbia fatto altre sviste anche se questa volta credo di aver gestito tutti i casi, nel frattempo modifico il file

**Comment by gpelisset** [comment]
Si, dovrebbe funzionare.

**Comment by gpelisset** [comment]
In realta' ho trovato una riduzione diretta da $A_{TM}$ a $DECIDABLE_{TM}$ molto elegante.
La macchina di Turing
$f(\langle M, w \rangle)$ = "Su input x:
- interpreta $x = \langle M', w'\rangle$.
- Se tale interpretazione fallisce, esegui $M(w)$ e accetta di conseguenza
- Esegui contemporaneamente, un passo a testa, $M'(w')$ e $M(w)$. Se qualcuna delle due accetta, accetta. Se terminano entrambe, rifiuta.
"

L'idea della correttezza sta nel fatto che se $M$ accetta $w$, $x$ viene sempre e comunque accettato.
Se $M$ va in loop su $x$, si accetta solo se $x$ e' della forma $\langle M', w'\rangle$ e $M'$ accetta $w'$.
Se $M$ rifiuta $x$, allora $x$ viene accettato  solo se $x$ e' della forma $\langle M', w'\rangle$ e $M'$ accetta $w'$.

Questo offre una riduzione a $DECIDABLE_{TM}$. Comunque la riduzione a $\overline{DECIDABLE_{TM}}$ va bene uguale.
