### ISSUE TITLE
[Error] Problema All-NFA

### ISSUE THREAD

**Issue by gpelisset** [Exyss/university-notes#68]
### Nome del file da correggere

Automi

### Numero della pagina da correggere

44

### Descrizione dell'errore ed eventuale correzione proposta

Nella seconda implicazione, e' vero che $N$, essendo un $All-NFA$ e' automaticamente un $NFA$, ma se lo considerassimo come un $NFA$, il suo linguaggio sarebbe diverso (nel senso che possono esistere stringhe che considerandolo come $NFA$ portano su uno stato accettante che non verrebbero accettate lo si considerasse come $All-NFA$ perche' non tutti i rami sono su uno stato accettante).

Il modo piu' semplice di aggiustarlo, mi sembra, e' riporporre una dimostrazione simile a quella che trasforma un $NFA$ $N = (Q, \Sigma, \delta, q_0, F_N)$ in un $DFA$ $D = (P(Q), \Sigma, \delta, E( \lbrace q_0 \rbrace), F)$ solamente che qui bisogna definire gli stati accettanti di $D$ come $F = \lbrace \tilde{Q} | Q \subseteq F_N \rbrace$. In questo caso si deve trasformare un $All-NFA$ in $DFA$ e non mi sembra vi sia un modo semplice per ridurre l'$All-NFA$ in un $NFA$.

### Screenshot dell'errore

![Screenshot from 2024-09-10 17-15-53](https://github.com/user-attachments/assets/929d8336-2e79-44df-8180-f38508a44ef1)

**Comment by Exyss** [comment]
Non sono d'accordo. Un All NFA è un NFA, punto. Non possono esserci stringhe che si comportano diversamente perché considerandolo come un NFA non alteriamo in alcun modo la struttura della macchina, visto che essa stessa è un NFA.

**Comment by gpelisset** [comment]
Ok, forse mi sono espresso male. Un ALL NFA e' un NFA dal punto di vista strutturale (la segnatura di $\delta$ e' uguale), ma non dal punto di vista della computazione visto che un All NFA accetta una stringa se e solo se tutti i rami di computazione finiscono su uno stato in $F$ mentre invece un NFA accetta $w$ se e solo se almeno uno dei rami di computazione accetta.

Ad esempio, se $N$ e' un NFA e su $w$ ha due rami di computazione di cui uno finisce in uno stato di $F$ e l'altro in uno stato non di $F$, $N$ accetta $w$. Ma se considero $N$ come un $All-NFA$ $N$ non accetterebbe $w$ perche' non tutti i rami di computazione finiscono su uno stato di $F$. Quindi il linguaggio di $N$ cambia a seconda che consideriamo $N$ un $NFA$ o un $All-NFA$.

Spero di esseremi espresso meglio.

**Comment by Exyss** [comment]
Beh no. Il tuo ragionamento è corretto ma non si applica a questo caso. Certo, un NFA può accettare più stringhe di un All NFA, ma in questo caso stiamo considerando il contrario.

Un All NFA non può accettare più stringhe di un NFA definito esattamente uguale ad esso poiché anche quel NFA accetterà su ogni singolo ramo. Le due macchine sono esattamente uguali. Non è che vedendolo come un NFA allora la macchina accetterà più stringhe.

Un cubo è un rettangolo, ma non è che se lo vedo come un rettangolo allora acquisisce qualche proprietà aggiuntiva.

**Comment by Exyss** [comment]
Sì così mi è più chiaro

**Comment by gpelisset** [comment]
Quando tu dici
> Un All NFA non può accettare meno stringhe di un NFA definito esattamente uguale ad esso poiché anche quel NFA accetterà su ogni singolo ramo.

questa non e' la definizione data sopra di All NFA. 
Per come un All-NFA e' definito non e' detto che per ogni input, o tutti i rami accettano, o tutti rifiutano. Proprio perche' possono esistere degli input per cui alcuni rami accettano ed altri rifiutano, il linguaggio di $N$ considerato come All-NFA puo' essere piu' piccolo di quello di $N$ considerato come NFA.

Per i cubi e rettangoli, se il concetto di cubo e' ben posto, cosa vuol dire che un cubo ha un determinato volume? Cambio la definizione di volume e cambia tutto. Cosi', per una quintupla $(Q, \Sigma, \delta, q_0, F)$, cambio cosa vuol dire che la quintupla accetta una stringa, e cambia il suo linguaggio.
