### ISSUE TITLE
[Enhancement] Calcolo delle Probabilità - P. 11-12 (13-14 of 67)

### ISSUE THREAD

**Issue by matypist** [Exyss/university-notes#7]
Propongo di rivedere il seguente esempio di "incongruenza logica", quello che volevi realmente trasmettere penso sia che per applicare la formula i casi totali devono essere equiprobabili; mentre per come nei tuoi appunti è descritto attualmente l'esempio l'"incongruenza logica" farebbe pensare di più, almeno a mio avviso, ad un errore di identificazione di quali elementi fanno parte dell'insieme ambiente che potrebbe commettere chi deve applicare la formula in esperimenti di questo genere

---

![image](https://user-images.githubusercontent.com/69389461/214969856-4ced1834-0958-43c2-8855-99a20187353c.png)
![image](https://user-images.githubusercontent.com/69389461/214969929-f3870da6-5a69-4ea1-a02e-42047ba5a1f8.png)

**Comment by Exyss** [comment]
Concordo che incongruenza logica non è il massimo come scelta di parole
