### ISSUE TITLE
[?] Calcolo delle Probabilità - P.14 (16 of 67)

### ISSUE THREAD

**Issue by matypist** [Exyss/university-notes#8]
Sicuro che l'insieme complementare di "Lanci tutti diversi tra loro" sia "Lanci tutti uguali tra loro"?

Non potremmo considerare ad esempio anche esiti come "12344" lanci **non** tutti diversi tra loro visto che è uscito 2 volte il 4?

**Comment by Exyss** [comment]
È un errore, non so perché ci sia scritto. L'evento dovrebbe essere "Almeno un lancio diverso", il cui complementare è appunto "Nessun lancio diverso = Tutti lanci uguali". Ho corretto, grazie
